// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAkhQ410lexSLFXzf9d4DUlKXzH5mEe53Y',
    appId: '1:971826640241:web:19ea0c51c994af85ea32d0',
    messagingSenderId: '971826640241',
    projectId: 'pertemuan5-arka-6b35a',
    authDomain: 'pertemuan5-arka-6b35a.firebaseapp.com',
    storageBucket: 'pertemuan5-arka-6b35a.firebasestorage.app',
    measurementId: 'G-JCM1SX6RV5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbtYbkCC-UPo6L9ad8fZHgiRC2GQ2GC2c',
    appId: '1:971826640241:android:486b5cff99918e29ea32d0',
    messagingSenderId: '971826640241',
    projectId: 'pertemuan5-arka-6b35a',
    storageBucket: 'pertemuan5-arka-6b35a.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAkhQ410lexSLFXzf9d4DUlKXzH5mEe53Y',
    appId: '1:971826640241:web:0fb652b1447701cbea32d0',
    messagingSenderId: '971826640241',
    projectId: 'pertemuan5-arka-6b35a',
    authDomain: 'pertemuan5-arka-6b35a.firebaseapp.com',
    storageBucket: 'pertemuan5-arka-6b35a.firebasestorage.app',
    measurementId: 'G-HQQ85SG4WY',
  );
}
